// Lights Out - toggle puzzle, every level generated by random presses so it is always solvable
const N = 5, S = 72, OX = 320 - (N * S) / 2, OY = 70;

MCC.game({
  id: 'lights-out',
  title: 'Lights Out',
  width: 640, height: 480,
  scored: false,
  instructions: ['Click a light to switch it and its four neighbours.', 'Turn off every light to finish the level.', 'Try to use as few moves as possible!'],

  init(g) { g.level = 1; this.make(g); g.state = 'title'; },
  start(g) { g.level = 1; this.make(g); },

  make(g) {
    g.on = Array(N * N).fill(false);
    const presses = Math.min(12, 2 + g.level);
    const used = new Set();
    while (used.size < presses) used.add(g.randInt(0, N * N - 1));
    used.forEach((i) => this.toggle(g, i % N, Math.floor(i / N)));
    if (g.on.every((v) => !v)) return this.make(g);
    g.moves = 0; g.par = presses; g.win = 0;
  },

  toggle(g, x, y) {
    for (const [dx, dy] of [[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]]) {
      const X = x + dx, Y = y + dy;
      if (X >= 0 && Y >= 0 && X < N && Y < N) g.on[Y * N + X] = !g.on[Y * N + X];
    }
  },

  update(g, dt) {
    if (g.win > 0) { g.win -= dt; if (g.win <= 0) { g.level++; this.make(g); } return; }
    if (g.mouse.clicked) {
      const x = Math.floor((g.mouse.x - OX) / S), y = Math.floor((g.mouse.y - OY) / S);
      if (x >= 0 && y >= 0 && x < N && y < N) {
        this.toggle(g, x, y); g.moves++; g.sfx('click');
        if (g.on.every((v) => !v)) { g.win = 1.4; g.sfx('win'); }
      }
      if (g.mouse.y > 440 && g.mouse.x > 500) { g.level = Math.max(1, g.level); this.make(g); }
    }
  },

  demo(g) { g.level = 6; this.make(g); g.moves = 3; },

  draw(g, ctx) {
    const bg = ctx.createRadialGradient(320, 240, 50, 320, 240, 420);
    bg.addColorStop(0, '#1a2a4a'); bg.addColorStop(1, '#05070f');
    ctx.fillStyle = bg; ctx.fillRect(0, 0, g.W, g.H);
    g.text('LIGHTS OUT', 320, 34, 34, '#ffe45a', '#4a3000', 'center', g.FONT_TITLE);
    ctx.fillStyle = '#10141e'; g.roundRect(OX - 12, OY - 12, N * S + 24, N * S + 24, 14); ctx.fill();
    ctx.strokeStyle = '#3a4a6a'; ctx.lineWidth = 3; ctx.stroke();
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
      const on = g.on[y * N + x], X = OX + x * S + 5, Y = OY + y * S + 5;
      if (on) { ctx.save(); ctx.shadowColor = '#ffd83a'; ctx.shadowBlur = 22; }
      const gr = ctx.createRadialGradient(X + S / 2 - 12, Y + S / 2 - 12, 4, X + S / 2, Y + S / 2, S / 1.3);
      if (on) { gr.addColorStop(0, '#fffbd0'); gr.addColorStop(0.5, '#ffd83a'); gr.addColorStop(1, '#e89a00'); }
      else { gr.addColorStop(0, '#4a5a7a'); gr.addColorStop(1, '#1a2238'); }
      ctx.fillStyle = gr; g.roundRect(X, Y, S - 10, S - 10, 10); ctx.fill();
      if (on) ctx.restore();
    }
    g.text('Level ' + g.level, 90, 120, 26, '#fff', null);
    g.text('Moves: ' + g.moves, 90, 160, 20, '#bfe6ff', null);
    g.text('Target: ' + g.par, 90, 190, 20, '#bfe6ff', null);
    g.button(500, 440, 120, 32, 'New Puzzle', ['#8fd0ff', '#3a8de0', '#1a5ab0']);
    if (g.win > 0) g.text('Lights Out!', 320, 250, 50, '#8dff6a', '#003a00', 'center', g.FONT_TITLE);
  },
});
